version: '3'
services:
  cli:
    image: composer:1.7
    volumes:
    - ./:/app
    working_dir: /app
    env_file:
    - ./.env
  web:
    image: php:7.2-apache
    volumes:
    - ./:/app
    working_dir: /app
    environment:
      APACHE_DOCUMENT_ROOT: /app/src/web
    env_file:
    - ./.env
    entrypoint: ['sh', '/app/.docker/web/entrypoint.sh']
